name: Run maven build

on:
  push:
    branches-ignore:
      - 'master'

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Maven Verify
        run: mvn -B clean test
